# -*- coding: utf-8 -*-
"""End Module Exam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1435Gb27FVrEauCo6y8xUrwrzJnT-nY2D

**Q.3) Print**

1

0 1

0 1 0

1 0 1 0

1 0 1 0 1
"""

k=1
for i in range(0,6):
  for j in range(1,i+1):
    print("0"if k%2==0 else "1",end=" ")
    k+=1
  print()

"""**Q.1) Convert given hrs & mins in second**"""

Hour=int(input("Enter hours"))
Minutes=int(input("Enter minutes"))
Second=(Hour*3600)+(Minutes*60)
print(Hour,"Hours and Minutes",Minutes,"Minutes are total",Second,"Seconds")

"""Q.2) Write code to find the average of ‘n’
numbers entered by the user to function avg ( ).
Ex: avg (10, 20, 30, 40) => average is: 70
avg (5, 10, 15) => average is: 10 

"""

ls=[]
n=int(input("How many no you want to enter: "))
for i in range(1,n+1):
  n1=int(input("Enter any number: "))
  ls.append(n1)
print(ls)
avg=sum(ls)/len(ls)
print("Average=",avg)

"""***Q.5) Create class ***"""

class Maths:
  def __init__(self,a,b):
    self.a=a
    self.b=b
  def Add(self):
    self.add=self.a+self.b
  def Div(self):
    self.div=self.a/self.b
  def Sub(self):
    self.sub=self.a-self.b
  def Mul(self):
    self.mul=self.a*self.b
  def Print(self):
    print("Addition: ",self.add,"Division: ",self.div,"Substraction: ",self.sub,"Multiplication: ",self.mul)

m=Maths(6,4)

m.Add()

m.Div()

m.Sub()

m.Mul()

m.Print()

"""Q.9) Accept String & print only alternate
characters on a string. 
"""

S=input("Enter a String: ")
print("Alternate Character are:",S[1::2])

"""Q.6) Read file & count numbers of digit
alphabets & symbols 

"""

S=input("Enter a String")
d=l=0
for i in S:
  if i.isdigit():
    d=d+1
  elif i.isalpha():
    l=l+1
  else:
    continue
print("Letters:",l)
print("Alphabates:",l)

"""**Q.10) Create menu driven code for**

1) Accept 2 numbers

2) Add

3) Sub

4) Mul

5) Div

6) Exit
"""

def add(num1,num2):
  print(num1+num2)
def sub(num1,num2):
  print(num1-num2)
def mul(num1,num2):
  print(num1*num2)
def div(num1,num2):
  print(num1//num2)
num1=int(input("enter the number"))
num2=int(input("enter the number"))
print("enter the operator (+,-,*,//) ")
ch= input()
if ch=="+":
  print(str(add(num1,num2)))
elif ch=="-":
  print(str(sub(num1,num2)))
elif ch=="*":
  print(str(mul(num1,num2)))
elif ch=="//":
  print(str(div(num1,num2)))
else:
  print("not available")